using System.Collections.Generic;
using System.Linq;
using System.Text;
using Olviia.CodeMap.Core.Model;
using Olviia.CodeMap.Core.Resolution;

namespace Olviia.CodeMap.Core.Rendering
{
    /// <summary>Turns parsed modules into Markdown: one main index with the public API, one file per module with everything.</summary>
    public sealed class MarkdownRenderer
    {
        /// <summary>File name of the main index.</summary>
        public const string MainFileName = "INDEX.md";

        /// <summary>Folder of the per-module files, relative to the main index.</summary>
        public const string ModuleFolder = "index";

        private const string GeneratedNotice = "<!-- Generated by CodeMap. Do not edit. -->";

        /// <summary>Renders every output document.</summary>
        /// <param name="modules">Modules in display order, each with its files.</param>
        /// <param name="overrides">Source of "override of" / "implements" labels.</param>
        /// <returns>The main index first, then one file per module that declares any type.</returns>
        public IReadOnlyList<RenderedFile> Render(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides)
        {
            var output = new List<RenderedFile> { new RenderedFile(MainFileName, RenderMain(modules, overrides)) };
            foreach (ModuleFiles module in modules.Where(HasTypes))
                output.Add(new RenderedFile(ModulePath(module.Module), RenderModule(module, overrides)));
            return output;
        }

        private static string RenderMain(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides)
        {
            var text = new StringBuilder();
            text.Append("# API Index\n").Append(GeneratedNotice).Append('\n');

            text.Append("\n## Modules\n| Module | Root | Depends on |\n|---|---|---|\n");
            foreach (ModuleFiles module in modules)
                text.Append("| ").Append(module.Module.Name).Append(" | ").Append(Roots(module.Module)).Append(" | ").Append(References(module.Module)).Append(" |\n");

            var undocumented = new List<string>();
            foreach (ModuleFiles module in modules.Where(HasTypes))
            {
                text.Append("\n## ").Append(module.Module.Name).Append('\n');
                text.Append("Internals: [").Append(ModulePath(module.Module)).Append("](").Append(ModulePath(module.Module)).Append(")\n");
                AppendTypes(text, module, true, overrides, undocumented);
            }
            AppendUndocumented(text, undocumented);
            return text.ToString();
        }

        private static string RenderModule(ModuleFiles module, OverrideResolver overrides)
        {
            var text = new StringBuilder();
            text.Append("# ").Append(module.Module.Name).Append('\n').Append(GeneratedNotice).Append('\n');
            text.Append("Root: ").Append(Roots(module.Module)).Append('\n');
            text.Append("Depends on: ").Append(References(module.Module)).Append('\n');

            var undocumented = new List<string>();
            AppendTypes(text, module, false, overrides, undocumented);
            AppendUndocumented(text, undocumented);
            return text.ToString();
        }

        private static void AppendTypes(StringBuilder text, ModuleFiles module, bool externalOnly, OverrideResolver overrides, List<string> undocumented)
        {
            foreach (List<Declared<TypeEntry>> parts in GroupPartials(module))
            {
                TypeEntry type = parts[0].Item;
                if (externalOnly && !type.Access.IsVisibleOutsideAssembly())
                    continue;
                // Partial types live in several files; then every member needs its own file name.
                bool severalFiles = parts.Select(p => p.File.Path).Distinct().Count() > 1;

                // Each part of a partial type may add base types and only one usually carries the doc comment.
                string[] baseTypes = parts.SelectMany(p => p.Item.BaseTypes).Distinct().ToArray();
                Declared<TypeEntry> documented = parts.FirstOrDefault(p => !p.Item.Doc.IsEmpty);
                DocComment typeDoc = documented.File != null ? documented.Item.Doc : DocComment.None;

                text.Append("\n### ").Append(AccessPrefix(type.Access)).Append(KindWord(type.Kind)).Append(' ').Append(TypeName(type.Name));
                if (baseTypes.Length > 0)
                    text.Append(" : ").Append(string.Join(", ", baseTypes));
                text.Append(" — ").Append(string.Join(", ", parts.Select(p => RelativePath(module.Module, p.File.Path) + ":" + p.Item.Line))).Append('\n');
                AppendDoc(text, typeDoc, string.Empty);

                if (typeDoc.IsEmpty)
                    undocumented.Add(Undocumented(module, type.Name, RelativePath(module.Module, parts[0].File.Path), type.Line));

                if (type.Kind == TypeKind.Enum)
                {
                    text.Append(string.Join(", ", type.Members.Select(m => m.Signature))).Append('\n');
                    continue;
                }

                foreach (Declared<TypeEntry> part in parts)
                {
                    string file = RelativePath(module.Module, part.File.Path);
                    foreach (MemberEntry member in part.Item.Members)
                    {
                        if (externalOnly && !member.Access.IsVisibleOutsideAssembly())
                            continue;

                        text.Append("- `").Append(AccessPrefix(member.Access)).Append(member.Signature).Append("` ")
                            .Append(severalFiles ? file : string.Empty).Append(':').Append(member.Line);
                        string origin = overrides.OriginOf(part.Item, member);
                        if (origin.Length > 0)
                            text.Append(" (").Append(origin).Append(')');
                        text.Append('\n');
                        AppendDoc(text, member.Doc, "  ");

                        // A delegate's only member shares the delegate's own doc, so it is reported once, above.
                        if (member.Doc.IsEmpty && type.Kind != TypeKind.Delegate)
                            undocumented.Add(Undocumented(module, type.Name + "." + member.Name, file, member.Line));
                    }
                }
            }
        }

        private static void AppendDoc(StringBuilder text, DocComment doc, string indent)
        {
            if (doc.Summary.Length > 0)
                text.Append(indent).Append(doc.Summary).Append('\n');
            else if (doc.IsInherited)
                text.Append(indent).Append("(inherited doc)\n");

            string[] parameters = doc.Params.Where(p => p.Value.Length > 0).Select(p => p.Key + ": " + p.Value).ToArray();
            if (parameters.Length > 0)
                text.Append(indent).Append(string.Join(" · ", parameters)).Append('\n');
            if (doc.Returns.Length > 0)
                text.Append(indent).Append("→ ").Append(doc.Returns).Append('\n');
        }

        private static void AppendUndocumented(StringBuilder text, List<string> undocumented)
        {
            if (undocumented.Count == 0)
                return;
            text.Append("\n## Undocumented\n");
            foreach (string line in undocumented)
                text.Append(line).Append('\n');
        }

        private static string Undocumented(ModuleFiles module, string name, string file, int line)
        {
            return "- " + module.Module.Name + ": `" + name + "` " + file + ":" + line;
        }

        // Types with the same name in one module are parts of a partial type; keeps first-seen order.
        private static IEnumerable<List<Declared<TypeEntry>>> GroupPartials(ModuleFiles module)
        {
            var groups = new List<List<Declared<TypeEntry>>>();
            var byName = new Dictionary<string, List<Declared<TypeEntry>>>();
            foreach (FileEntry file in module.Files)
            {
                foreach (TypeEntry type in file.Types)
                {
                    if (!byName.TryGetValue(type.Name, out List<Declared<TypeEntry>> group))
                    {
                        byName[type.Name] = group = new List<Declared<TypeEntry>>();
                        groups.Add(group);
                    }
                    group.Add(new Declared<TypeEntry>(type, file));
                }
            }
            return groups;
        }

        private static bool HasTypes(ModuleFiles module)
        {
            return module.Files.Any(f => f.Types.Count > 0);
        }

        private static string ModulePath(ModuleInfo module)
        {
            return ModuleFolder + "/" + module.Name + ".md";
        }

        private static string Roots(ModuleInfo module)
        {
            return string.Join(", ", module.RootPaths);
        }

        private static string References(ModuleInfo module)
        {
            return module.References.Count == 0 ? "—" : string.Join(", ", module.References);
        }

        // Paths are shown relative to the module root, which the module table already lists.
        private static string RelativePath(ModuleInfo module, string path)
        {
            foreach (string root in module.RootPaths.OrderByDescending(r => r.Length))
            {
                string prefix = root.TrimEnd('/') + "/";
                if (path.StartsWith(prefix, System.StringComparison.OrdinalIgnoreCase))
                    return path.Substring(prefix.Length);
            }
            return path;
        }

        // Generic names go in backticks, otherwise Markdown viewers treat <T> as an HTML tag.
        private static string TypeName(string name)
        {
            return name.IndexOf('<') >= 0 ? "`" + name + "`" : name;
        }

        private static string AccessPrefix(Access access)
        {
            switch (access)
            {
                case Access.Protected: return "protected ";
                case Access.ProtectedInternal: return "protected internal ";
                case Access.Internal: return "internal ";
                case Access.PrivateProtected: return "private protected ";
                default: return string.Empty;
            }
        }

        private static string KindWord(TypeKind kind)
        {
            switch (kind)
            {
                case TypeKind.Struct: return "struct";
                case TypeKind.Interface: return "interface";
                case TypeKind.Enum: return "enum";
                case TypeKind.Record: return "record";
                case TypeKind.Delegate: return "delegate";
                default: return "class";
            }
        }

        // An entry together with the file it was declared in.
        private readonly struct Declared<T>
        {
            public readonly T Item;
            public readonly FileEntry File;

            public Declared(T item, FileEntry file)
            {
                Item = item;
                File = file;
            }
        }
    }
}
