using System.Collections.Generic;
using System.Linq;
using System.Text;
using Olviia.CodeMap.Core.Model;
using Olviia.CodeMap.Core.Modules;
using Olviia.CodeMap.Core.Resolution;

namespace Olviia.CodeMap.Core.Rendering
{
    /// <summary>
    /// Turns parsed modules into Markdown: one main index with the module table and the ports
    /// (see <see cref="PortConvention"/>), and one file per module with everything else.
    /// </summary>
    public sealed class MarkdownRenderer
    {
        /// <summary>File name of the main index.</summary>
        public const string MainFileName = "INDEX.md";

        /// <summary>Folder of the per-module files, relative to the main index.</summary>
        public const string ModuleFolder = "index";

        private const string GeneratedNotice = "<!-- Generated by CodeMap. Do not edit. -->";

        /// <summary>Renders every output document.</summary>
        /// <param name="modules">Modules in display order, each with its files.</param>
        /// <param name="overrides">Source of "override of" / "implements" labels.</param>
        /// <returns>The main index first, then one file per module that declares any type.</returns>
        public IReadOnlyList<RenderedFile> Render(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides)
        {
            var implementers = new ImplementerResolver(modules);
            var output = new List<RenderedFile> { new RenderedFile(MainFileName, RenderMain(modules, overrides, implementers)) };
            foreach (ModuleFiles module in modules.Where(HasTypes))
                output.Add(new RenderedFile(ModulePath(module.Module), RenderModule(module, modules, overrides, implementers)));
            return output;
        }

        private static string RenderMain(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides, ImplementerResolver implementers)
        {
            var text = new StringBuilder();
            text.Append("# API Index\n").Append(GeneratedNotice).Append('\n');
            text.Append("Module table and ports only. Offered ports are each module's API; everything else is in the linked module files.\n");

            text.Append("\n## Modules\n| Module | Pure C# | Root | Depends on | Used by |\n|---|---|---|---|---|\n");
            foreach (ModuleFiles module in modules)
            {
                // Modules without types get no file, so there is nothing to link to.
                string name = HasTypes(module) ? "[" + module.Module.Name + "](" + ModulePath(module.Module) + ")" : module.Module.Name;
                text.Append("| ").Append(name)
                    .Append(" | ").Append(module.Module.IsEngineFree ? "yes" : string.Empty)
                    .Append(" | ").Append(Roots(module.Module))
                    .Append(" | ").Append(References(module.Module))
                    .Append(" | ").Append(UsedBy(module.Module, modules))
                    .Append(" |\n");
            }

            var undocumented = new List<string>();
            foreach (ModuleFiles module in modules)
            {
                List<List<Declared<TypeEntry>>> ports = GroupPartials(module).Where(p => RoleOf(module, p).Length > 0).ToList();
                if (ports.Count == 0)
                    continue;

                text.Append("\n## ").Append(module.Module.Name).Append('\n');
                List<List<Declared<TypeEntry>>> offered = ports.Where(p => PortConvention.IsOffered(RoleOf(module, p))).ToList();
                if (offered.Count > 0)
                {
                    text.Append("Offered ports:\n");
                    AppendTypes(text, module, offered, true, overrides, implementers, undocumented);
                }

                // Ports the module needs from outside: one line each, enough to find the adapter.
                foreach (IGrouping<string, List<Declared<TypeEntry>>> role in ports.Where(p => !PortConvention.IsOffered(RoleOf(module, p))).GroupBy(p => RoleOf(module, p)))
                {
                    text.Append(offered.Count > 0 ? "\n" : string.Empty).Append(role.Key).Append(" ports:\n");
                    foreach (List<Declared<TypeEntry>> port in role)
                    {
                        TypeEntry type = port[0].Item;
                        IReadOnlyList<string> adapters = implementers.ImplementersOf(type.Name);
                        text.Append("- `").Append(AccessPrefix(type.Access)).Append(KindWord(type.Kind)).Append(' ').Append(type.Name).Append("` ")
                            .Append(RelativePath(module.Module, port[0].File.Path)).Append(':').Append(type.Line)
                            .Append(" → ").Append(adapters.Count > 0 ? string.Join(", ", adapters) : "not implemented").Append('\n');
                    }
                }
            }
            AppendUndocumented(text, undocumented);
            return text.ToString();
        }

        private static string RenderModule(ModuleFiles module, IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides, ImplementerResolver implementers)
        {
            var text = new StringBuilder();
            text.Append("# ").Append(module.Module.Name).Append('\n').Append(GeneratedNotice).Append('\n');
            text.Append("Root: ").Append(Roots(module.Module)).Append('\n');
            text.Append("Pure C#: ").Append(module.Module.IsEngineFree ? "yes" : "no").Append('\n');
            text.Append("Depends on: ").Append(References(module.Module)).Append('\n');
            text.Append("Used by: ").Append(UsedBy(module.Module, modules)).Append('\n');

            var undocumented = new List<string>();
            AppendTypes(text, module, GroupPartials(module), false, overrides, implementers, undocumented);
            AppendUndocumented(text, undocumented);
            return text.ToString();
        }

        private static void AppendTypes(StringBuilder text, ModuleFiles module, IEnumerable<List<Declared<TypeEntry>>> types, bool externalOnly,
            OverrideResolver overrides, ImplementerResolver implementers, List<string> undocumented)
        {
            foreach (List<Declared<TypeEntry>> parts in types)
            {
                TypeEntry type = parts[0].Item;
                if (externalOnly && !type.Access.IsVisibleOutsideAssembly())
                    continue;
                // Partial types live in several files; then every member needs its own file name.
                bool severalFiles = parts.Select(p => p.File.Path).Distinct().Count() > 1;

                // Each part of a partial type may add base types and only one usually carries the doc comment.
                string[] baseTypes = parts.SelectMany(p => p.Item.BaseTypes).Distinct().ToArray();
                Declared<TypeEntry> documented = parts.FirstOrDefault(p => !p.Item.Doc.IsEmpty);
                DocComment typeDoc = documented.File != null ? documented.Item.Doc : DocComment.None;

                text.Append("\n### ").Append(AccessPrefix(type.Access)).Append(KindWord(type.Kind)).Append(' ').Append(TypeName(type.Name));
                if (baseTypes.Length > 0)
                    text.Append(" : ").Append(string.Join(", ", baseTypes));
                text.Append(" — ").Append(string.Join(", ", parts.Select(p => RelativePath(module.Module, p.File.Path) + ":" + p.Item.Line))).Append('\n');
                AppendDoc(text, typeDoc, string.Empty);
                if (type.Kind == TypeKind.Interface)
                {
                    IReadOnlyList<string> adapters = implementers.ImplementersOf(type.Name);
                    if (adapters.Count > 0)
                        text.Append("Implemented by: ").Append(string.Join(", ", adapters)).Append('\n');
                }

                if (typeDoc.IsEmpty)
                    undocumented.Add(Undocumented(module, type.Name, RelativePath(module.Module, parts[0].File.Path), type.Line));

                if (type.Kind == TypeKind.Enum)
                {
                    text.Append(string.Join(", ", type.Members.Select(m => m.Signature))).Append('\n');
                    continue;
                }

                foreach (Declared<TypeEntry> part in parts)
                {
                    string file = RelativePath(module.Module, part.File.Path);
                    foreach (MemberEntry member in part.Item.Members)
                    {
                        if (externalOnly && !member.Access.IsVisibleOutsideAssembly())
                            continue;

                        text.Append("- `").Append(AccessPrefix(member.Access)).Append(member.Signature).Append("` ")
                            .Append(severalFiles ? file : string.Empty).Append(':').Append(member.Line);
                        string origin = overrides.OriginOf(part.Item, member);
                        if (origin.Length > 0)
                            text.Append(" (").Append(origin).Append(')');
                        text.Append('\n');
                        AppendDoc(text, member.Doc, "  ");

                        // A delegate's only member shares the delegate's own doc, so it is reported once, above.
                        // Implementations and overrides inherit the doc of the member they come from, like <inheritdoc/>.
                        if (member.Doc.IsEmpty && type.Kind != TypeKind.Delegate && origin.Length == 0)
                            undocumented.Add(Undocumented(module, type.Name + "." + member.Name, file, member.Line));
                    }
                }
            }
        }

        private static void AppendDoc(StringBuilder text, DocComment doc, string indent)
        {
            if (doc.Summary.Length > 0)
                text.Append(indent).Append(doc.Summary).Append('\n');

            string[] parameters = doc.Params.Where(p => p.Value.Length > 0).Select(p => p.Key + ": " + p.Value).ToArray();
            if (parameters.Length > 0)
                text.Append(indent).Append(string.Join(" · ", parameters)).Append('\n');
            if (doc.Returns.Length > 0)
                text.Append(indent).Append("→ ").Append(doc.Returns).Append('\n');
        }

        private static void AppendUndocumented(StringBuilder text, List<string> undocumented)
        {
            if (undocumented.Count == 0)
                return;
            text.Append("\n## Undocumented\n");
            foreach (string line in undocumented)
                text.Append(line).Append('\n');
        }

        private static string Undocumented(ModuleFiles module, string name, string file, int line)
        {
            return "- " + module.Module.Name + ": `" + name + "` " + file + ":" + line;
        }

        // Port role of a type, read from the folder of its first part; empty when it is not a port.
        private static string RoleOf(ModuleFiles module, List<Declared<TypeEntry>> parts)
        {
            return PortConvention.RoleOf(RelativePath(module.Module, parts[0].File.Path));
        }

        // Types with the same name in one module are parts of a partial type; keeps first-seen order.
        private static List<List<Declared<TypeEntry>>> GroupPartials(ModuleFiles module)
        {
            var groups = new List<List<Declared<TypeEntry>>>();
            var byName = new Dictionary<string, List<Declared<TypeEntry>>>();
            foreach (FileEntry file in module.Files)
            {
                foreach (TypeEntry type in file.Types)
                {
                    if (!byName.TryGetValue(type.Name, out List<Declared<TypeEntry>> group))
                    {
                        byName[type.Name] = group = new List<Declared<TypeEntry>>();
                        groups.Add(group);
                    }
                    group.Add(new Declared<TypeEntry>(type, file));
                }
            }
            return groups;
        }

        private static bool HasTypes(ModuleFiles module)
        {
            return module.Files.Any(f => f.Types.Count > 0);
        }

        private static string ModulePath(ModuleInfo module)
        {
            return ModuleFolder + "/" + module.Name + ".md";
        }

        private static string Roots(ModuleInfo module)
        {
            return string.Join(", ", module.RootPaths);
        }

        private static string References(ModuleInfo module)
        {
            return module.References.Count == 0 ? "—" : string.Join(", ", module.References);
        }

        // Reverse of References: what breaks when this module changes.
        private static string UsedBy(ModuleInfo module, IReadOnlyList<ModuleFiles> modules)
        {
            string[] users = modules.Where(m => m.Module.References.Contains(module.Name)).Select(m => m.Module.Name).ToArray();
            return users.Length == 0 ? "—" : string.Join(", ", users);
        }

        // Paths are shown relative to the module root, which the module table already lists.
        private static string RelativePath(ModuleInfo module, string path)
        {
            foreach (string root in module.RootPaths.OrderByDescending(r => r.Length))
            {
                string prefix = root.TrimEnd('/') + "/";
                if (path.StartsWith(prefix, System.StringComparison.OrdinalIgnoreCase))
                    return path.Substring(prefix.Length);
            }
            return path;
        }

        // Generic names go in backticks, otherwise Markdown viewers treat <T> as an HTML tag.
        private static string TypeName(string name)
        {
            return name.IndexOf('<') >= 0 ? "`" + name + "`" : name;
        }

        private static string AccessPrefix(Access access)
        {
            switch (access)
            {
                case Access.Protected: return "protected ";
                case Access.ProtectedInternal: return "protected internal ";
                case Access.Internal: return "internal ";
                case Access.PrivateProtected: return "private protected ";
                default: return string.Empty;
            }
        }

        private static string KindWord(TypeKind kind)
        {
            switch (kind)
            {
                case TypeKind.Struct: return "struct";
                case TypeKind.Interface: return "interface";
                case TypeKind.Enum: return "enum";
                case TypeKind.Record: return "record";
                case TypeKind.Delegate: return "delegate";
                default: return "class";
            }
        }

        // An entry together with the file it was declared in.
        private readonly struct Declared<T>
        {
            public readonly T Item;
            public readonly FileEntry File;

            public Declared(T item, FileEntry file)
            {
                Item = item;
                File = file;
            }
        }
    }
}
