using System.Collections.Generic;
using System.Linq;
using System.Text;
using Olviia.CodeMap.Core.Model;
using Olviia.CodeMap.Core.Resolution;

namespace Olviia.CodeMap.Core.Rendering
{
    /// <summary>
    /// Turns parsed modules into Markdown: one main index with the module table and everything visible
    /// outside its assembly, and one file per module with its internal and private members.
    /// </summary>
    public sealed class MarkdownRenderer
    {
        /// <summary>File name of the main index.</summary>
        public const string MainFileName = "INDEX.md";

        /// <summary>Folder of the per-module files, relative to the main index.</summary>
        public const string ModuleFolder = "index";

        private const string GeneratedNotice = "<!-- Generated by CodeMap. Do not edit. -->";
        private const string Undocumented = "undocumented";

        /// <summary>Renders every output document.</summary>
        /// <param name="modules">Modules in display order, each with its files.</param>
        /// <param name="overrides">Source of "override of" / "implements" labels.</param>
        /// <returns>The main index first, then one file per module that declares any type.</returns>
        public IReadOnlyList<RenderedFile> Render(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides)
        {
            var implementers = new ImplementerResolver(modules);
            var output = new List<RenderedFile> { new RenderedFile(MainFileName, RenderMain(modules, overrides, implementers)) };
            foreach (ModuleFiles module in modules.Where(HasTypes))
                output.Add(new RenderedFile(ModulePath(module.Module), RenderModule(module, modules, overrides, implementers)));
            return output;
        }

        private static string RenderMain(IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides, ImplementerResolver implementers)
        {
            var text = new StringBuilder();
            text.Append("# API Index\n").Append(GeneratedNotice).Append('\n');
            text.Append("Module table and everything visible outside its assembly. Internal and private members are in the linked module files.\n");

            text.Append("\n## Modules\n| Module | Pure C# | Root | Depends on | Used by |\n|---|---|---|---|---|\n");
            foreach (ModuleFiles module in modules)
            {
                // Modules without types get no file, so there is nothing to link to.
                string name = HasTypes(module) ? "[" + module.Module.Name + "](" + ModulePath(module.Module) + ")" : module.Module.Name;
                text.Append("| ").Append(name)
                    .Append(" | ").Append(module.Module.IsEngineFree ? "yes" : string.Empty)
                    .Append(" | ").Append(Roots(module.Module))
                    .Append(" | ").Append(References(module.Module))
                    .Append(" | ").Append(UsedBy(module.Module, modules))
                    .Append(" |\n");
            }

            foreach (ModuleFiles module in modules)
            {
                var section = new StringBuilder();
                AppendTypes(section, module, GroupPartials(module), true, overrides, implementers);
                if (section.Length > 0)
                    text.Append("\n## ").Append(module.Module.Name).Append('\n').Append(section);
            }
            return text.ToString();
        }

        private static string RenderModule(ModuleFiles module, IReadOnlyList<ModuleFiles> modules, OverrideResolver overrides, ImplementerResolver implementers)
        {
            var text = new StringBuilder();
            text.Append("# ").Append(module.Module.Name).Append('\n').Append(GeneratedNotice).Append('\n');
            text.Append("Root: ").Append(Roots(module.Module)).Append('\n');
            text.Append("Pure C#: ").Append(module.Module.IsEngineFree ? "yes" : "no").Append('\n');
            text.Append("Depends on: ").Append(References(module.Module)).Append('\n');
            text.Append("Used by: ").Append(UsedBy(module.Module, modules)).Append('\n');
            text.Append("Internal and private members only; the rest is in ").Append(MainFileName).Append(".\n");

            AppendTypes(text, module, GroupPartials(module), false, overrides, implementers);
            return text.ToString();
        }

        // visible = true writes what other assemblies can see (main index); false writes the rest (module file).
        // A visible type with hidden members appears in both: full header in the main index, bare header in the module file.
        private static void AppendTypes(StringBuilder text, ModuleFiles module, IEnumerable<List<Declared<TypeEntry>>> types, bool visible,
            OverrideResolver overrides, ImplementerResolver implementers)
        {
            foreach (List<Declared<TypeEntry>> parts in types)
            {
                TypeEntry type = parts[0].Item;
                bool typeVisible = type.Access.IsVisibleOutsideAssembly();
                if (visible && !typeVisible)
                    continue;
                // A hidden type goes whole into the module file; a visible one only sends its hidden members there.
                // Members are already narrowed to their type's access, so a hidden type has no visible members.
                bool fullType = typeVisible == visible;
                List<(Declared<TypeEntry> part, MemberEntry member)> members = parts
                    .SelectMany(p => p.Item.Members.Select(m => (p, m)))
                    .Where(pm => pm.m.Access.IsVisibleOutsideAssembly() == visible)
                    .ToList();
                if (!fullType && members.Count == 0)
                    continue;

                // Partial types live in several files; then every member needs its own file name.
                bool severalFiles = parts.Select(p => p.File.Path).Distinct().Count() > 1;

                text.Append("\n### ").Append(AccessPrefix(type.Access)).Append(KindWord(type.Kind)).Append(' ').Append(TypeName(type.Name));
                if (fullType)
                {
                    // Each part of a partial type may add base types.
                    string[] baseTypes = parts.SelectMany(p => p.Item.BaseTypes).Distinct().ToArray();
                    if (baseTypes.Length > 0)
                        text.Append(" : ").Append(string.Join(", ", baseTypes));
                }
                text.Append(" — ").Append(string.Join(", ", parts.Select(p => RelativePath(module.Module, p.File.Path) + ":" + p.Item.Line))).Append('\n');

                if (fullType)
                {
                    // Only one part of a partial type usually carries the doc comment.
                    Declared<TypeEntry> documented = parts.FirstOrDefault(p => !p.Item.Doc.IsEmpty);
                    text.Append(documented.File != null ? documented.Item.Doc.Summary : Undocumented).Append('\n');
                    if (type.Kind == TypeKind.Interface)
                    {
                        IReadOnlyList<string> adapters = implementers.ImplementersOf(type.Name);
                        if (adapters.Count > 0)
                            text.Append("Implemented by: ").Append(string.Join(", ", adapters)).Append('\n');
                    }
                    if (type.Kind == TypeKind.Enum)
                    {
                        text.Append(string.Join(", ", type.Members.Select(m => m.Signature))).Append('\n');
                        continue;
                    }
                    // A delegate's only member repeats the delegate itself.
                    if (type.Kind == TypeKind.Delegate)
                        continue;
                }

                foreach ((Declared<TypeEntry> part, MemberEntry member) in members)
                {
                    text.Append("- `").Append(AccessPrefix(member.Access)).Append(member.Signature).Append("` ")
                        .Append(severalFiles ? RelativePath(module.Module, part.File.Path) : string.Empty).Append(':').Append(member.Line);
                    // Implementations and overrides inherit the doc of the member they come from, like <inheritdoc/>.
                    string origin = overrides.OriginOf(part.Item, member);
                    if (origin.Length > 0)
                        text.Append(" (").Append(origin).Append(')');
                    if (member.Doc.Summary.Length > 0)
                        text.Append(" — ").Append(member.Doc.Summary);
                    else if (origin.Length == 0)
                        text.Append(" — ").Append(Undocumented);
                    text.Append('\n');
                }
            }
        }

        // Types with the same name in one module are parts of a partial type; keeps first-seen order.
        private static List<List<Declared<TypeEntry>>> GroupPartials(ModuleFiles module)
        {
            var groups = new List<List<Declared<TypeEntry>>>();
            var byName = new Dictionary<string, List<Declared<TypeEntry>>>();
            foreach (FileEntry file in module.Files)
            {
                foreach (TypeEntry type in file.Types)
                {
                    if (!byName.TryGetValue(type.Name, out List<Declared<TypeEntry>> group))
                    {
                        byName[type.Name] = group = new List<Declared<TypeEntry>>();
                        groups.Add(group);
                    }
                    group.Add(new Declared<TypeEntry>(type, file));
                }
            }
            return groups;
        }

        private static bool HasTypes(ModuleFiles module)
        {
            return module.Files.Any(f => f.Types.Count > 0);
        }

        private static string ModulePath(ModuleInfo module)
        {
            return ModuleFolder + "/" + module.Name + ".md";
        }

        private static string Roots(ModuleInfo module)
        {
            return string.Join(", ", module.RootPaths);
        }

        private static string References(ModuleInfo module)
        {
            return module.References.Count == 0 ? "—" : string.Join(", ", module.References);
        }

        // Reverse of References: what breaks when this module changes.
        private static string UsedBy(ModuleInfo module, IReadOnlyList<ModuleFiles> modules)
        {
            string[] users = modules.Where(m => m.Module.References.Contains(module.Name)).Select(m => m.Module.Name).ToArray();
            return users.Length == 0 ? "—" : string.Join(", ", users);
        }

        // Paths are shown relative to the module root, which the module table already lists.
        private static string RelativePath(ModuleInfo module, string path)
        {
            foreach (string root in module.RootPaths.OrderByDescending(r => r.Length))
            {
                string prefix = root.TrimEnd('/') + "/";
                if (path.StartsWith(prefix, System.StringComparison.OrdinalIgnoreCase))
                    return path.Substring(prefix.Length);
            }
            return path;
        }

        // Generic names go in backticks, otherwise Markdown viewers treat <T> as an HTML tag.
        private static string TypeName(string name)
        {
            return name.IndexOf('<') >= 0 ? "`" + name + "`" : name;
        }

        private static string AccessPrefix(Access access)
        {
            switch (access)
            {
                case Access.Protected: return "protected ";
                case Access.ProtectedInternal: return "protected internal ";
                case Access.Internal: return "internal ";
                case Access.PrivateProtected: return "private protected ";
                case Access.Private: return "private ";
                default: return string.Empty;
            }
        }

        private static string KindWord(TypeKind kind)
        {
            switch (kind)
            {
                case TypeKind.Struct: return "struct";
                case TypeKind.Interface: return "interface";
                case TypeKind.Enum: return "enum";
                case TypeKind.Record: return "record";
                case TypeKind.Delegate: return "delegate";
                default: return "class";
            }
        }

        // An entry together with the file it was declared in.
        private readonly struct Declared<T>
        {
            public readonly T Item;
            public readonly FileEntry File;

            public Declared(T item, FileEntry file)
            {
                Item = item;
                File = file;
            }
        }
    }
}
